---
title: "Godspeed"
date: 2003-02-01 23:10:51
slug: 2003/02/02/godspeed
layout: post
---


I just saw the news. Not sure yet what to say, except for this:

Godspeed to the scientists who lost their lives today in their pursuit to
bring our species closer to the stars. May you rest in piece.
