---
title: "Word of the day: \"Kaputtage\""
date: 2007-12-14
slug: 2007/12/14/word-of-the-day-kaputtage
tags: en, humor
layout: post
---


### kaputtage

kaputt-age (kä-pŏŏ’tĭj) -- noun

Derived from “outage”, describing the state of something being really, you
know, _kaputt_.

(Yeah, I've made that up.)
