---
title: "Erkenntnis"
date: 2007-04-30
slug: 2007/04/30/erkenntnis
tags:
- internet
lang: de
layout: post
---


Das Internet ist wie eine externe Version dieses total wahnsinnigen Teils
meines überaktiven Unterbewusstseins, der mir dauernd ungefragt lustige
Filmschnipsel, Zitate, blöde Songs und uralte Gags auftischt.
