---
title: "Erkenntnis"
date: 2007-04-30 15:06:12
slug: 2007/04/30/erkenntnis
tags: de, internet
layout: post
---


Das Internet ist wie eine externe Version dieses total wahnsinnigen Teils
meines überaktiven Unterbewusstseins, der mir dauernd ungefragt lustige
Filmschnipsel, Zitate, blöde Songs und uralte Gags auftischt.
