---
title: "Mini Review: \"Ocean's 13\""
date: 2007-06-09
slug: 2007/06/09/mini-review-oceans-13
tags:
- movies
- reviews
layout: post
---


It’s funny, highly entertaining, and dripping coolness.

Go watch it.
