---
title: "Aufwachen!"
date: 2007-01-15
slug: 2007/01/15/aufwachen
tags: leben
lang: de
layout: post
---


Seit letzter Woche steht jeden Morgen an der U-Bahn-Station ein entfernt an
[Gunther von Hagens][1] erinnernder Mann und hebt eine Publikation mit dem
etwas aufdringlichen Namen [Erwachet!][2] in die Luft. Die sich daraus
ergebende Ironie, daß er das Blatt noch schlaftrunkenden Menschen auf dem Weg
in die Arbeit ins Gesicht hält, scheint ihm nicht aufzufallen.

[1]: http://de.wikipedia.org/wiki/Gunther_von_Hagens
[2]: http://
