---
title: "Mini Review: \"Iron Man\""
date: 2008-05-12 22:24:21
slug: 2008/05/12/mini-review-iron-man
tags: en, movies, reviews
layout: post
---


Quite a hoot! The lady and I enjoyed it thoroughly. Looking forward to the
inevitable sequel.

Worth the money.
