---
title: "Mini Review: Need For Speed Carbon (Demo), Xbox 360"
date: 2008-04-01 19:57:43
slug: 2008/04/01/mini-review-need-for-speed-carbon-demo-xbox-360
tags: 360, en, reviews
layout: post
---


#### Preface

* ~1GB download.

#### Lasting impressions

* Bad framerate issues. (No joke. Pretty choppy at times.)
* Good sound design, especially in the “angry polygon dude yelling at me from his car”-type cutscenes.
* Kinda (too) easy.

#### Verdict

* Meh.
* It’s no Burnout Paradise (demo).
* Srsly—it’s no Burnout Paradise (demo).
