---
title: "Mini Review: \"Children of Men\""
date: 2008-03-24
slug: 2008/03/24/mini-review-children-of-men
tags:
- movies
- reviews
layout: post
---


Wonderful movie that manages to be hopeful and dystopian at the same time.
Great cast.The “block under siege” scenes where everyone was united in awe had
me in tears.

Go buy/rent.
