---
title: Apple users are from Mars, Android users are from Venus
abstract: It's the godsdamn console wars all over again, I swear.
date: 2012-09-12
layout: post
slug: 2012-09-12-apple-vs-android
lang: en
tags:
- android
- apple
- wtf
---

So today Apple might/will/should announce the iPhone 5.  Which, of course, means there'll be a _hilarious avalanche_ of delightful "art" by curiously insecure[^1] Android users, just like [this one](https://plus.google.com/110255737428907780217/posts):

![Sheep running towards a badly photoshopped Apple Store](https://dl.dropbox.com/u/7298/blog/2012-09-12-apple-store-artwork.jpeg "Sheep running towards a badly photoshopped Apple Store")

Haha, it's funny because it's *utter bullshit*.

I guess Apple users are from Mars, Android users are from Venus!!!1  Or something.  Bloody hell, I'm already sick and tired of the predictable Apple user bashing.

It's not just that many conscious Android users I've met don't understand what I like about iOS, it's that they _don't want_ to hear why.  Not all of them, mind.  Just …many.  You prefer Android?  Great, your choice, have fun.  Me, I like iOS better.  That doesn't make me retarded or a sheep or a mindless drone.

But your willful ignoring _my_ reasons, preferences and ability to decide make *you* look like a proper fuckstick.  The door swings both ways, of course: rabid iOS fans are no better.

And when I talk with those people, it becomes clear that their minds are so set on "the one true OS/device/whatever" that they're convinced the other side has nothing new or better to offer.  Also, that the other side is nothing but braindead drones following a cult.  But that is a ridiculous notion, especially when talking about iOS and Android.

Different people look for different things: favourite screen sizes, how multitasking is handled, whether or not there should be hardware buttons, how configurable everything is etc.  And that's how it's supposed to be.  Just remember that maxing out, rooting or skinning your Android handset won't make you Neo; much like how meticulously re-ordering the icons on your iPhone doesn't mean you're <del>the goddamn Batman</del> Jony Ive.

*You've made a hardware/software choice.*  Congratulations.  My guess is it was the right one for you.  Now live with it, own it.  And please understand that your choice won't improve retroactively by belittling others.  The other party is not at fault, so suck it up, you pussies.

If you can't grok that: Go die in a fire, you righteous cunts.

[^1]: If they're not insecure at all, why do they feel the need to LOL at people who chose differently?
