---
title: Apple users are from Mars, Android users are from Venus
abstract: It's the godsdamn console wars all over again, I swear.
date: 2012-09-12
layout: post
slug: 2012-09-12-apple-vs-android
lang: en
tags:
- android
- apple
- wtf
---

So today Apple might/will/should announce the iPhone 5.  Which, of course, means there'll be a _hilarious avalanche_ of delightful "art" by curiously insecure[^1] Android users, just like [this one](https://plus.google.com/110255737428907780217/posts):

![Sheep running towards a badly photoshopped Apple Store](https://dl.dropbox.com/u/7298/blog/2012-09-12-apple-store-artwork.jpeg "Sheep running towards a badly photoshopped Apple Store")

Haha, it's funny because it's *utter bullshit*.

I guess Apple users are from Mars, Android users are from Venus!!!1  Or something.  Bloody hell, I'm already sick and tired of the predictable Apple user bashing.

It's not just that many conscious Android users I've met don't understand what I like about iOS, it's that they don't want to hear why.  Not all of them, mind.  Just …many.  You prefer Android?  Great, your choice, have fun.  Me, I like iOS better.  That doesn't make me retarded or a sheep or a mindless drone.

But your willful ignoring _my_ reasons, preferences and ability to decide make *you* look like a proper fuckstick.  The door swings both ways, of course: rabid iOS fans are no better.

Different people look for different things.  Maxing out your Android handset doesn't make you Neo, and meticulously ordering the icons on your iPhone doesn't make you fucking Jonathan Ive.

*You've made a hardware/software choice.*  Ace.  My guess is it was the right one for you.  Now live with it, own it.  And please understand that your choice won't improve retroactively by belittling others.

If you can't grok that: Go die in a fire, you righteous cunts.

[^1]: If they're not insecure at all, why do they feel the need to LOL at people who chose differently?
