---
title: RSS Feed Changes
abstract: Adios, Feedburner.
date: 2012-09-25
layout: post
lang: en
slug: 2012/09/25/rss-feed-changes
tags:
- this here site
---

After years of negligence, [Feedburner is on its way out](http://techcrunch.com/2012/09/24/feedburner-experiencing-stat-issues-api-to-shut-down/).  Unfortunately, this means this site's RSS feed URL is changing, too.

So, please update your feed reader.  The new URL is [carlo.zottmann.org/rss/index.xml](http://carlo.zottmann.org/rss/index.xml); the current one will temporarily redirect any requests for 30 days, but that'll be it.
