---
title: "Post-It #30"
abstract: Bash one-liners, Flickr vs Yahoo!, low-innovation internet, draft posts in jekyll, a great zombie-related short.
date: 2012-06-05
layout: post
lang: en
---


**This is useful.**  ["Bash One-Liners Explained"][bash-oneliners] is laying out in some detail the hows, whats and whys of bash's power in a number of examples.  Part I deals with files, and I've learned a few new tricks!  Bookmarked.

**This is depressing.**  I started at Yahoo just a few months after Yahoo! had snatched up Flickr, and I remember being happy about them doing it, for they were "the good guys".  I remember the [delicious acquisition][blog-yahoo-delicious] shortly afterwards, too.  I also remember what happened then, or better, what didn't happen, and how we were all a bit confused by the stalling.  So Gizmodo's ["How Yahoo Killed Flickr and Lost the Internet"][yahoo-flickr] was enlightening.

**This is sad.**  ["When Will this Low-Innovation Internet Era End?"][low-innovation], asks HBR's Justin Fox.  I think that's a damn good question.  Related: Doug Humphrey's [_"we will still need an Internet, once we are done putting the Entertainet in place"_][doug-humphrey].  (Via [Tim O'Reilly on G+][gplus-oreilly].)

**This is practical.**  I was complaining about [Jekyll][jekyll] not allowing for real draft posts, but then I found [a simple way around that particular problem][gist-jekyll-drafts].  Works for me, but as always, YMMV.

**Not your average zombie short.**	This is good: ["Spoiler"][vimeo-spoiler] is a gripping, really well made short movie about "normal life" after mankind dodged the zombie outbreak bullet.  No splatter, just intense and emotional story telling.

<iframe src="http://player.vimeo.com/video/35665030?title=0&amp;byline=0&amp;portrait=0&amp;color=62a2b5" width="650" height="366" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>


[bash-oneliners]: http://www.catonmat.net/blog/bash-one-liners-explained-part-one/
[blog-yahoo-delicious]: /2005/12/10/yahoo-buying-del-icio-us/
[doug-humphrey]: http://www.listbox.com/member/archive/247/2012/06/sort/time_rev/page/1/entry/5:28/20120603154838:1B7FD88C-ADB5-11E1-8E95-AFA41BD92087/
[gist-jekyll-drafts]: https://gist.github.com/2870636
[gplus-oreilly]: https://plus.google.com/u/0/107033731246200681024/posts/FwrcZbkMMdm
[jekyll]: http://jekyllrb.com
[low-innovation]: http://blogs.hbr.org/fox/2012/04/low-innovation-internet-era.html
[vimeo-spoiler]: http://vimeo.com/35665030
[yahoo-flickr]: http://gizmodo.com/5910223/how-yahoo-killed-flickr-and-lost-the-internet
