---
title: "Post-It #34"
abstract: The history of the NRA, the future of medicine, the inherent dangers of biotechnology, space funding, and Tesla.
date: 2013-04-21
layout: post
lang: en
tags:
- post-it
- biotech
- medicine
- nra
- space
- tesla
---


Today's links are a few months old already, actually.  They were sitting in my `Post-It Inbox.mmd` file for a while and I just didn't get around to putting them in a post.  Well, shit happens.  :)

---

[How NRA’s true believers converted a marksmanship group into a mighty gun lobby](http://m.washingtonpost.com/politics/how-nras-true-believers-converted-a-marksmanship-group-into-a-mighty-gun-lobby/2013/01/12/51c62288-59b9-11e2-88d0-c4cf65c3ad15_story.html): If you want to know where they are coming from (both historically and politically), this _Washington Post_ article is quite enlightening.

---

[The Future of Medicine Is Now: Medical Innovations - WSJ.com](http://online.wsj.com/article/SB10001424127887323530404578205692226506324.html): A super-exciting rundown of some current[^1] treatments for cancer or defective organs.

[^1]: "Current"—in this context—means four months ago, i.e. end of 2012.

---

[Regulators Discover a Hidden Viral Gene in Commercial GMO Crops](http://independentsciencenews.org/commentaries/regulators-discover-a-hidden-viral-gene-in-commercial-gmo-crops/): The worst part? Humans might be susceptible to the viral gene as well. Terrifying prospects, really. For all the looking to the future (which I *do* welcome, mind) man should not forget what this particular bit of the closing paragraph expresses so succinctly.

> Biotechnology, it is often forgotten, is not just a technology. It is an experiment in the proposition that human institutions can perform adequate risk assessments on novel living organisms.

---

[Tesla Is The New Apple — The Tesla Collection — Medium](https://medium.com/the-tesla-collection-1/e36e6e21b2c): 

> In five or six years, electric vehicles are going to offer 500 miles of range. Assuming solar charging becomes more mainstream over that same period, the proposition for new car buyers will be simple: EVs will have longer range than gas-powered cars, effectively zero lifetime fuel cost, and zero emissions. […] All of this assumes purely linear improvements in the technology — with no radical breakthrough in battery storage.

I kind of suspect that these days, Janis Joplin would ask God for a [Model S](http://www.teslamotors.com/models) instead.

---

[Launch Party: a crowdfunding revolution ignites the next space race | The Verge](http://www.theverge.com/2013/1/31/3929342/the-stars-on-a-shoestring-amateurs-ignite-grassroots-space-race): The final frontier is approached with substantial help from amateurs and enthusiasts (like myself).

I have a really, *really* hard time expressing how exciting I find the current developments in (aero-)space technology!

---

And speaking of space, here's a deleted scene from Mass Effect:

![Danger in the cockpit of the Normandy 2](https://dl.dropboxusercontent.com/u/7298/blog/2013-04-21-masseffect-spin.gif)
