---
title: "Post-It #33"
abstract: Standing up for your truths, videogame movie adaptions, videogames violence, the history of Boing Boing and a paraplegic woman controlling robotic limbs with her brain.
date: 2013-01-27
layout: post
lang: en
tags:
- post-it
- principles
- videogames
- movies
- violence
- boing boing
- robotics
---

**Sanding slippery slopes.**  ["Never Lie About Who You Really Are"](http://blogs.hbr.org/pallotta/2012/12/never-lie-about-who-you-really-are.html) by NPR's Dan Pallotta is a strong essay for *not* letting things slide.  It may be tempting to just ignore stupidity and ignorance coming my way, but ultimately _someone_ has to pay a price, either me (by dying a little bit inside) or someone else (think customer care people having to deal with bugs/oversights in software or some such).

> So you’re not gay. You can still develop the strength to stand up for your truths. Stop trying to think outside the box. Start thinking outside the closet.

**Do it right, please, or not at all.** [How Hollywood Should Adapt Videogames](http://www.rockpapershotgun.com/2012/12/18/how-hollywood-should-adapt-videogames/): Interesting, lengthy essay about games being turned into movies, with a spotlight on the _Assassin's Creed_, _Splinter Cell_ and _Deus Ex: Human Revolution_ deals currently in the works.

**On violence in videogames.**  It's about a month old at that point, but Nathan Grayson's ["Why Aren’t We Discussing Videogame Violence?"](http://www.rockpapershotgun.com/2012/12/28/why-arent-we-discussing-videogame-violence/) is still a timely, really good, important post on the goddamn dead elephant in the room.

> If gaming’s detractors say one thing, we say the opposite. Gaming causes violence? No. There is absolutely no problem with the fact that most big-budget games spill enough blood to make the Red Sea’s name literal. None whatsoever.

**The history of Boing Boing.**  [FastCompany's lengthy tale of how Boing Boing came to be](http://www.fastcompany.com/1702167/inside-wild-wacky-profitable-world-boing-boing) is an interesting read.  I don't actively visit BB that often, but I always found their breadth of topics quite enjoyable nonetheless.

**From the HOLY CRAP YES PLEASE department:**  CBS' segment ["Breakthrough: Robotic limbs moved by the mind"](http://www.cbsnews.com/video/watch/?id=50137987n) is quite the thing.  The short version: Paraplegic woman undergoes brain surgery and can now move robotic arms and hands with her brain, with the signals going through two hardware ports in her head.

<object width="480" height="270"><param name="movie" value="http://can.cbs.com/thunder/player/chrome/canplayer.swf?pid=q1CMMTYNDjO_&partner=cbs&gen=1"></param><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param><embed width="480" height="270" src="http://can.cbs.com/thunder/player/chrome/canplayer.swf?pid=q1CMMTYNDjO_&partner=cbs&gen=1" allowFullScreen="true" allowScriptAccess="always" type="application/x-shockwave-flash"></embed></object>

Seeing this and thinking about it makes my scalp tingle.  It's a great time to be alive.
