---
title: On "evolving languages"
date: 2013-02-19
layout: post
lang: en
---

_"Awesome"_ is the new _"good"_.

_"Amazing"_ is the new _"nice"_.

_"X totally destroyed/killed Y"_ is the new _"Y is slightly inconvenienced by X"_.

_"The best thing ever"_ is the new _"I'll be amused by this for the next 2 minutes."_

_"A new, fun way to do XYZ"_ is the new _"Let me waste your precious time"_.

**You fucksticks broke my favourite language.**
