---
title: "Post-It #32"
abstract: Counting those Stephen Colberts, new spacesuits, stem cell research tripling mice life spans, and the mystery of the dark night sky explained.
date: 2013-01-17
layout: post
lang: en
tags:
- post-it
- stephen colbert
- nasa
- space
- longevity
- physics
---

**One of the great satirists of our time:**  [How Many Stephen Colberts Are There?](http://www.nytimes.com/2012/01/08/magazine/stephen-colbert.html?pagewanted=all): An enjoyable look at one of my favorite satirists.  Towards the end there's a short excerpt from the long list of his "exploits" — it's quite astounding, really.

**It's Buzz Lightyear!**  [NASA’s Z-1 spacesuit prototype looks familiar.](http://moonandback.com/2012/12/21/nasas-z-1-spacesuit-looks-remarkably-like-buzz-lightyears-videos/)  What most people don't know is that design-wise, the current line of NASA's hard-vacuum-capable space suits is roughly 40 years old.  Fourty years!  And people laugh about Russian Soyuz tech…

**Let's grow really old.**  [Old Mice Made "Young"—May Lead to Anti-Aging Treatments](http://news.nationalgeographic.com/news/2012/01/120106-aging-mice-stem-cells-old-young-science-health/): 

> To [stem-cell expert Johnny Huard’s] astonishment, the treated mice lived an average of 71 days—50 more than expected, and the equivalent of an 80-year-old human living to be 200, he said.

The scientists suspect that the young stem cells the mice were injected with secreted _something_ that influenced the host bodies in a good way, causing slowed aging. They are still puzzled at what that mysterious secretion is.

**Why is the sky dark at night?**  Interesting question, [answered by the MinutePhysics people](http://www.youtube.com/watch?v=gxJ4M7tyLRE):

<iframe width="650" height="365" src="http://www.youtube.com/embed/gxJ4M7tyLRE" frameborder="0" allowfullscreen></iframe>
