---
title: ★ Hi, I'm Carlo.
abstract: Coder, runner, husband, spy.
layout: post
---


G'day, you've reached the personal site of Carlo Zottmann.  I'm a [freelance
software developer](http://municode.de), minimalist runner, videogames 
enthusiast, coffee devotee and husband from Munich, Germany.

![That's me.](//dl.dropbox.com/u/7298/blog/me.jpg)

I build "applications" or "sites" for them so-called "internets".  Among my
past and present projects are [Servus for Mac](https://servus.io), a tool to
quickly share files wrapped in your own preview pages via Dropbox;
[foto-bundesliga](http://foto-bundesliga.de), a German-language league game 
site for photographers; TwerpScan, a Twitter contact list management tool 
(online and frequented by many a user for more than four years); and
[Ephemera](https://github.com/carlo/ephemera-coss), a Mac tool for Instapaper
enthusiasts with ebook readers (open-sourced by now). Since I'm running with
the cool kids, all of my (public) code is available on
[Github](http://github.com/carlo).

Comments are disabled as the most prolific comment authors in the past were
usually the ones trying to sell me stuff like "Semi-Original Penis Replacement
Lamps", and I really don't need that.  If you read something here and feel
like discussing it, shoot me a [twoot](http://twitter.com/municode) or drop me
a line via [Google+](https://plus.google.com/117556235540402405674).


* * *

Copyright ©2001-present Carlo Zottmann.  With notable exceptions, this site's
content is [available for non-commercial reuse](http://creativecommons.org/licenses/by-nc-nd/3.0/).

* * *

<small>
**Impressum & inhaltlich Verantwortlicher gemäß §10 Absatz 3 MDStV:**
Carlo Zottmann, Zeisigweg 30, 81827 München, Tel ++49-151-651-81827,
carlo@zottmann.org. **Haftungshinweis:** Trotz sorgfältiger inhaltlicher
Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links. Für
den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber
verantwortlich.
</small>
